
server:
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: myuser
    password: mypassword
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    # Kafka bootstrap servers
    bootstrap-servers: localhost:9095,localhost:9096,localhost:9097

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

bot:
  token: 8102512240:AAFyzXdH7cDZWWcOI-8jAuYud-3DJ0Jch3Y
  username: hubEvent_bot
  chatId: 5871294619